<?php
// $Id$

/*
 * Implements hook_menu
 *
 * Grab the path node/add/animation/%, so we can link directly from archive
 * pages to a form where this archive already is selected.
 *
 */
function timeline_animation_menu() {
  $items['node/add/animation/%'] = array(
    'title' => 'Timeline Animation',
    'title callback' => 'check_plain',
    'page callback' => 'animation_add',
    'page arguments' => array(3),
    'access callback' => 'node_access',
    'access arguments' => array('create', 'animation'),
    'description' => 'Create a new animation',
    'file' => 'timeline_animation.pages.inc',
  );
  
  return $items;
}

/*
 * Implements hook_node_insert
 *
 * In case of a new animation, add it to the queue, so it will be created by the
 * next cron run.
 *
 */

function timeline_animation_node_insert($node) {

  if ($node->type == 'animation') {
    $queue = DrupalQueue::get('animations_queue');
    $queue->deleteQueue();
    $queue->createQueue();  // There is no harm in trying to recreate existing.

    $queue->createItem($node->nid);
    timeline_animation_cron();
  }
}

/*
 * Implements hook_cron
 *
 * Create queued animations
 *
 */

function timeline_animation_cron() {
  module_load_include('inc', 'timeline_animation', 'include/video_ffmpeg');

  $queue = DrupalQueue::get('animations_queue');
  $queue->createQueue();  // There is no harm in trying to recreate existing.

  while ($item = $queue->claimItem(300)) // claim the item for 5 minutes
  {
    // Get all required images
    $animation = node_load($item->data);

    if (!$animation) {
      // has been deleted??
      continue;
    }

    try {
    $result = db_query("
      SELECT f.uri
      FROM {records} r
      LEFT JOIN {file_managed} f
        ON f.fid = r.fid
      WHERE FLOOR(r.request_time / :frequency) * :frequency % :interval = 0
      AND r.request_time > :start_time
      AND r.request_time < :end_time
      ", array(
        ':frequency'  => 300,
        ':interval'   => 300 * $animation->timeline_animation_interval['und'][0]['value'],
        ':start_time' => $animation->timeline_animation_start['und'][0]['value'],
        ':end_time'   => $animation->timeline_animation_end['und'][0]['value'],
      ))
    ->fetchAssoc();
    } catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
    }
    // Do symlinking...
    foreach ($result as $record) {
      symlink($target, $link);
    }

    // Convert video
    $ffmpeg = new FfmpegVideo();
    $ffmpeg->convert_video("m . $item->data . img%04d.jpg", $converted, $dimensions);

    watchdog('timeline_animation', 'Creating animation for @item', array('@string' => $item->data));

    $queue->deleteItem($item);
  }
}

?>